### ISSUE TITLE
wrong skillchains showing

### ISSUE THREAD

**Issue by sebyg666** [Ivaar/Skillchains#1]
ok so ive know of this for a while now, the way you check which WS can skillchain with the elements currently applied to the mob is performed in a incorrect order.
WS's have elemental properties that take priorities and ur method does not apply this. for example if you have a sword equipped and you do red lotus blade (liquefaction) it will tell you that vorpal blade will do a fusion SC which is incorrect as the primary element of vorpal balde is scission and therefor will do a scission SC.

attached is a copy of my file with a couple extra blue spells also added
(please note if you are goin to try it you will need to change the font to a font you have or it wont show the text box)
(note 2, github does not support droppin lua files so i converted to text just for this)
i love this addon, it works great but wanted to fix it.

[skillchains.txt](https://github.com/Ivaar/Skillchains/files/742944/skillchains.txt)

**Comment by Ivaar** [comment]
I will have a look into this, the addon tries to keep track of what elements each mob in the surrounding area has effective then checks the elements vs your ws list to produce the onscreen text. Trust NPC's can mess this up (especially the ones released in the past year) and other unlisted skills. What you are describing is certainly a bug I wish to address as soon as I can. I do not have an active account as I haven't played ffxi in nearly 2 years. If you discover any more bugs please do let me know.

    On Tuesday, January 31, 2017 11:25 AM, sebyg666 <notifications@github.com> wrote:
 

 ok so ive know of this for a while now, the way you check which WS can skillchain with the elements currently applied to the mob is performed in a incorrect order.
WS's have elemental properties that take priorities and ur method does not apply this. for example if you have a sword equipped and you do red lotus blade (liquefaction) it will tell you that vorpal blade will do a fusion SC which is incorrect as the primary element of vorpal balde is scission and therefor will do a scission SC.attached is a copy of my file with a couple extra blue spells also added
(please note if you are goin to try it you will need to change the font to a font you have or it wont show the text box)
(note 2, github does not support droppin lua files so i converted to text just for this)
i love this addon, it works great but wanted to fix it.skillchains.txt—

**Comment by SammehFFXI** [comment]
Ivaar - I've added / customized some of your code last night.  (My coding skills aren't what yours are - this is *very* clean).

Anyway - I wanted to make sure pets were more represented as skillchains (specifically jug pets).  While they were recorded - if you were BST main it didn't show your pets abilities to continue the chain.  Only main hand weaponskills.

Also - I added some color to it.

Do you want me to do a pull/merge?  

Also - can you release it under normal windower license for redistribution/modification?

`--[[
Copyright © 2016, <<CharName>> of <<Server>>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of <<ADDON_NAME>>nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <<CHARNAME>> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
`

**Comment by Ivaar** [comment]
Sorry, I guess I didn't realize you posted a fix as I wasn't really keeping tabs on ffxi. I went ahead and added your changes. Thank you for your contribution.
