### ISSUE TITLE
show job abilities with sc properties

### ISSUE THREAD

**Issue by garzyan** [Ivaar/Skillchains#7]
hello. i got this issue, only when i play as dragoon, when I use jump or high jump, the skillchain addon show them as weaponskills being used, one of them show as avalance axe, the other i cant remember. anything i can do?

**Comment by Ivaar** [comment]
You can remove 317 from the list of message ids on line 50. I'll look into it more this weekend.

**Comment by garzyan** [comment]
i will try that :) thanks for replying

**Comment by MartelRagnarok** [comment]
Any word on this issue? Removing the 317 ID doesn't seem to prevent this anymore. No idea why.

**Comment by garzyan** [comment]
> Any word on this issue? Removing the 317 ID doesn't seem to prevent this anymore. No idea why.

well since i deleted the 317 on line 50, it have worked perfect for me. and it still works, so no idea why it dosn't work for you :(

**Comment by Ivaar** [comment]
I checked into it a few months ago, then forgot! Seems I need to revert skills.lua structure since category does not seem to be a good switch case anymore. The file is generated by another script which pulls the skillchain properties from the menu descriptions. I need to modify the update script and packet handling. Also, I've heard mention that windowers resources may need to be updated for DRG abilities. I'm not sure if that's true, but I will need to look into that too. I will try to get it updated after this weekend.
